### ISSUE TITLE
[feature]连写支持

### ISSUE THREAD

**Issue by Free-Aaron-Li** [thep0y/monaco-nerd-font#2]
如题，
请问该字体能否支持连写，例如：-->、->、!=、==之类能够转换成更为熟悉的字符
就像jetbrains mono一样：
![image](https://github.com/thep0y/monaco-nerd-font/assets/95997167/c1f00dbb-6b68-4555-8938-98705236f314)

**Comment by thep0y** [comment]
我从不用连写，有时间会看看能否添加。

**Comment by thep0y** [comment]
[release](https://github.com/thep0y/monaco-nerd-font/releases/latest)中已上传连字符字体，你可以试试看有无问题，因为我不使用连字符，所以不知道连字符的效果应该如何。

**Comment by Free-Aaron-Li** [comment]
测试了带有连字的两种类型字体，对常规连字支持很好
![image](https://github.com/thep0y/monaco-nerd-font/assets/95997167/29ad0235-994c-4859-ac1f-61ae8ace195c)

**Comment by thep0y** [comment]
那就关了这个issue吧
