### ISSUE TITLE
外接显示器时个别字母宽度异常

### ISSUE THREAD

**Issue by Silver-Ray** [thep0y/monaco-nerd-font#4]
字体在笔记本电脑上显示效果极佳，但是外接显示屏时有的字母被压缩，具体为体现为：
1. 使用“仅第二屏幕”模式时，字母m和其他的字母距离较近，如图所示：
![image](https://github.com/thep0y/monaco-nerd-font/assets/110368897/6208c394-5849-4ca4-9258-f3da73b978b9)
2. 使用“复制模式时以及在笔记本电脑上显示时，显示正常，效果如下：

复制模式显示屏显示：
![image](https://github.com/thep0y/monaco-nerd-font/assets/110368897/e4d591a9-5ff2-4cc8-aa44-94f9d0cada47)

复制模式笔记本屏幕显示：
![image](https://github.com/thep0y/monaco-nerd-font/assets/110368897/55441a47-7c2e-4ad6-bce0-b0185749873b)

3. VScode 和 Sublime 均出现该问题，**猜测与编辑器无关**：

sublime截图
![image](https://github.com/thep0y/monaco-nerd-font/assets/110368897/656f04cb-d2cc-4a79-8ba8-cfcd42171730)

电脑显示屏分辨率为2560\*1600，16寸16：10。显示器分辨率为2560\*1440，27寸16：9。我猜测可能与显示器和笔记本的屏幕长宽比不同有关，但是其他字体都没有出现该问题，不知道博主适配时使用的屏幕比例是否为16：9。

被这个问题困扰许久，不知道是否有解决方案，若有感谢告知！

**Comment by thep0y** [comment]
也许这并不是字体的问题，我与你之间的区别就是分辨率。

<img width="1225" alt="image" src="https://github.com/thep0y/monaco-nerd-font/assets/51874567/87f8b3a9-4888-4ba9-8715-27c962299902">

**Comment by Silver-Ray** [comment]
感谢回复，我测试了下应该是windows缩放的bug，启用125%缩放时出现了字体间距过近的问题，但是当我启用自定义缩放124%时，这个问题消失了，补一张我测试时候的图：
<img width="617" alt="Snipaste_2023-08-27_20-03-16" src="https://github.com/thep0y/monaco-nerd-font/assets/110368897/611e7e83-dd52-46be-b682-87dc291f8b1e">

这是调成124%后的效果，正常显示：
![image](https://github.com/thep0y/monaco-nerd-font/assets/110368897/c30c752b-e039-4a4d-a48e-c93c12176906)
